### ISSUE TITLE
Minor dependency update breaks this package

### ISSUE THREAD

**Issue by lukasmalkmus** [carbon-design-system/carbon-preprocess-svelte#53]
Not sure what went wrong here. Ran a batch of dependency updates (minor versions only) and suddenly seeing this error when building:

```bash
Error: Could not find a declaration file for module 'carbon-preprocess-svelte'. 'node_modules/carbon-preprocess-svelte/dist/index.mjs' implicitly has an 'any' type.
```

In my `svelte.config.js` I'm importing it like this:

```js
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import { optimizeImports, optimizeCss, icons } from 'carbon-preprocess-svelte';
```

This is the diff:

<img width="985" alt="Screenshot 2024-02-27 at 21 02 52" src="https://github.com/carbon-design-system/carbon-preprocess-svelte/assets/9931588/48cbd516-c87a-4f6b-ae9d-e654ca4c0b94">

I assume this package is not at fault but wanted to post it here for visibility.

**Comment by andrewrisse** [comment]
I'm also seeing this issue with V0.10.0.
```
Could not find a declaration file for module 'carbon-preprocess-svelte'. '/.../node_modules/carbon-preprocess-svelte/dist/index.mjs' implicitly has an 'any' type.
  There are types at '../node_modules/carbon-preprocess-svelte/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'carbon-preprocess-svelte' library may need to update its package.json or typings.
  ```

**Comment by lukasmalkmus** [comment]
🙌

**Comment by metonym** [comment]
Closing the loop here.

[v0.11.0](https://github.com/carbon-design-system/carbon-preprocess-svelte/releases/tag/v0.11.0) was released and is a complete library rewrite, specifically focusing on getting `optimizeCss` to a good stae.

How it pertains to this issue:

- Number of package dependencies is reduced
- Size of the distributed package is vastly reduced (~15 MB --> 100 kB)

@lukasmalkmus I notice in your example you are using the `icons` preprocessor. Unfortunately, I decided to remove all preprocessor and focus on `optimizeImports` and the `optimizeCss` plugin. I may revisit the `icons/pictograms/elements` preprocessors when I know the DX can be greater. The workaround would be to use components from `carbon-icons-svelte` instead of the preprocessor.

Please let me know if you run into any issues.

**Comment by lukasmalkmus** [comment]
Yeah, I noticed that. Not a big problem. Not gonna lie: I only included it because it was listed in the README and it felt sensible to use when I started diving into the carbon for svelte ecosystem.

There is one issue I need to double check to make sure it's not me doing something wrong: After updating my dependencies and enabling `optimizeImports` and `optimizeCss` again, I noticed a big reduction in CSS size but also the styling for my charts (via `@carbon/charts-svelte`) is now broken. I wonder if I had previously misconfigured `optimizeCss` and that problem is unrelated to this issue or if there is indeed a problem with the current release of this package and the carbon charts for svelte.

Will dig in a bit deeper after work and let you know!
